### ISSUE TITLE
By default, set dryRun to false

### ISSUE THREAD

**Issue by Elikill58** [wangyucode/sftp-upload-action#12]
I through this wasn't workign, because `dryRun` is on true by default. So, It wasn't uploading files.

Can you change default value for others users ?

**Comment by wangyucode** [comment]
Okay, I'll change the default value of `dryRun` to `false` in the next release.

**Comment by wangyucode** [comment]
https://github.com/wangyucode/sftp-upload-action/releases/tag/v1.4.7
