### ISSUE TITLE
`removeExtraFilesOnServer` is set by `dryRun`

### ISSUE THREAD

**Issue by andrsd** [wangyucode/sftp-upload-action#14]
https://github.com/wangyucode/sftp-upload-action/blob/f9898e65f068d6f63489f02b5f569fc0b94d9e4c/sftp.cjs#L20

This does not look right.

**Comment by wangyucode** [comment]
Yes, you are right, I will change this in the next release. Thanks.

**Comment by wangyucode** [comment]
https://github.com/wangyucode/sftp-upload-action/releases/tag/v1.4.7

**Comment by andrsd** [comment]
Thanks for the quick fix! Much appreciated.
