### ISSUE TITLE
Allow loading private keys from files

### ISSUE THREAD

**Issue by andrsd** [wangyucode/sftp-upload-action#15]
### Motivation

On self-hosted runners, we can already have SSH keys in place. So it would be nice to have an option to point this action to the file with the SSH key and use it. This way, we wouldn't have to create an extra SSH key through github secrets.

###  Suggestion

Allow `privateKey` param to take a file name. The code would first check if the value is an existing file and if so it would load the key - similar to what they do [here](https://www.npmjs.com/package/ssh2-sftp-client#sec-6-3). If not, then it would assume that the content is the key, i.e. the current behavior.

A solution via `privateKeyFileName` would be also fine, but the above seems more user friendly.

**Comment by andrsd** [comment]
Hope this makes sense. Let me know if more clarification is required.

**Comment by wangyucode** [comment]
It now supports pass file path as `privateKey` now
https://github.com/wangyucode/sftp-upload-action/releases/tag/v1.4.8

**Comment by andrsd** [comment]
I gave this a test today and it works as expected. Thank you so much for implementing this feature so quickly :+1:
