### ISSUE TITLE
dryRun does not default to false

### ISSUE THREAD

**Issue by iGoodie** [wangyucode/sftp-upload-action#18]
README suggests `dryRun` defaults to false. However it defaults to true

----

README suggests it's false
https://github.com/wangyucode/sftp-upload-action/blob/e0de1f266f2b720e61f81b77d64925ab00d87d91/README.md?plain=1#L21

But action.yml has it as true
https://github.com/wangyucode/sftp-upload-action/blob/e0de1f266f2b720e61f81b77d64925ab00d87d91/action.yml#L22-L24

**Comment by xam-ps** [comment]
Can confirm this bug. Didn't specify anything -> dryRun was active.

After adding "dryRun: false" everything was working as expected.

**Comment by arsenitem** [comment]
same here. Needed to update docs
