### ISSUE TITLE
Excluded folders are still deleted on remote location

### ISSUE THREAD

**Issue by matthijssn** [wangyucode/sftp-upload-action#19]
Hi,

First of all, great work with this component. Really usefull!

** Use case **
I'm trying to deploy a build result of a project to an SFTP location. The project has a downloads and photos folder, but since that's not part of the code base I prefer not to keep those folders in the git. So I need those folders (which are already in the remote location) to persist. Also, the API (backend) of the site is stored in the folder API, which is being handled by another step in my Github workflow, so that one needs to persist as well.

** Defined action **
 - name: Sync Frontend to ftp 
        uses: wangyucode/sftp-upload-action@v1.4.8
        with:     
          host: 'XXX.XXXXX.XXX'
          username: XXXXXX.XXX
          password: ${{ secrets.ftp_pwd }}          
          localDir: './dist'
          remoteDir: '/tst'    
          forceUpload: true  
          dryRun: false
          exclude: 'api/,photos/,/downloads/'
          removeExtraFilesOnServer: true     

** Expected result **
All existing files and folders removed on remote location, excluding the folders api, photos and downloads. After this, the new build result (stored in /dist) is being copied to the remote location

** Real result **
All existing files and folders are indeed removed, but also the api, photos and downloads folder. After this, the new build result (stored in /dist) is copied to the remote location. This causes that the persistent folders are gone.
Is my syntax incorrect, or is my usecase not possible? Thanks!

**Comment by wangyucode** [comment]
this issue has been fixed at  v1.4.9, and you should change `/download/` -> `download/`
