### ISSUE TITLE
SFTP Uploads Old Files

### ISSUE THREAD

**Issue by AllekP** [wangyucode/sftp-upload-action#21]
Hi I am experiencing an issue, where once a new push is done into the MAIN branch, the SFTP Uploads add old files to the upload list and not only the newer files.

<img width="665" alt="Screenshot 2023-02-21 at 19 44 34" src="https://user-images.githubusercontent.com/6542226/220420742-31e1f2a7-7904-4f7f-a03c-7e002d548f0b.png">

The only files that were updated and pushed.

<img width="952" alt="Screenshot 2023-02-21 at 19 46 08" src="https://user-images.githubusercontent.com/6542226/220420807-2435ed1f-31d6-4972-ad65-69bb163901a2.png">

This is my Workflow:

name: Upload complete repo (e.g. website) to a SFTP destination

on: [push]

jobs:
  Upload-to-SFTP:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code                     # Checkout the latest code
        uses: actions/checkout@v3

      - name: SFTP uploader
        uses: wangyucode/sftp-upload-action@v1.4.9
        with:
          host: ${{ secrets.HOST }} 
          port: ${{ secrets.PORT }} 
          username: ${{ secrets.USERNAME }} 
          privateKey: ${{ secrets.SSH_KEY }} 
          # localDir: 'dist'
          remoteDir: ${{ secrets.UPLOAD_DIR }}             # Optional. exclude patterns (glob) like .gitignore, use ',' to split, Default to ''.
          # dryRun: true 
          forceUpload: false

**Comment by wangyucode** [comment]
The modification time of files is the time they were checked out by `actions/checkout`,
so you should restore the modification time to the commit time first,
here is an action that can restore the modified time: https://github.com/marketplace/actions/git-restore-mtime

**Comment by AllekP** [comment]
Thanks for the information:

So i have implemented the restore modified time, when the upload happens it seems like it is also checking the server for new files.

I now getting the below. Instead of just uploading the newer files from the repo.

<img width="1081" alt="Screenshot 2023-02-22 at 11 58 35" src="https://user-images.githubusercontent.com/6542226/220586414-cd3e9db3-55cb-4469-a40f-eef8dab1dc20.png">

**Comment by AllekP** [comment]
How do I skip the **server has newer file:**   stuff?

**Comment by AllekP** [comment]
Do you have any feedback for me?

**Comment by wangyucode** [comment]
What the server skips is uploading, not checking. Only by comparing the modification time and size can we know whether a file needs to be uploaded. I didn't find any problems in your log, it did skip the files that don't need to be uploaded. 
I have published a new release `v2.0.3`
If you have a lot of files or the network is not good, you can consider another method: https://github.com/[wangyucode/crane](https://github.com/wangyucode/crane)
