### ISSUE TITLE
`removeExtraFilesOnServer`: Exclude files/folders

### ISSUE THREAD

**Issue by MickL** [wangyucode/sftp-upload-action#27]
Great project, thanks! I have a feature request tho:

`removeExtraFilesOnServer: true` is a nice option BUT it also deletes everything, e.g. sub-folders. When deploying a website to root '/' it also deletes sub-folders that may contain content that is not related to the website.

It would be nice to have an option to either:

- Don't delete sub-folders
- Specify specific files/folders that are not getting deleted

**Comment by wangyucode** [comment]
refactored the code in `v2.0.3`, and `exclude` should also applied when removing extra files. So after passing `exclude: ['not-remove/']` it will not touch the `not-remove` folder on the server
