### ISSUE TITLE
Reading all Files

### ISSUE THREAD

**Issue by NicoEv** [wangyucode/sftp-upload-action#32]
Hey,

is there any way to disable reading all the remote files, and just read the files that got edited in the commit ?

**Comment by daniego** [comment]
I'm looking for the same feature

**Comment by daniego** [comment]
It seems already implemented in `removeExtraFilesOnServer`, shouldn't be too difficult to implement in `readRemoteFiles`

**Comment by wangyucode** [comment]
it's using the `ssh2-sftp-client` library to list remote files and find files that exist in the local folder but are missing in the remote folder. This library **does not** actually read any file content, but only retrieves the file path and modification time. To prevent confusion, I changed 'reading' to 'found' in `v2.0.3`.
