### ISSUE TITLE
ExludeMode Ignore

### ISSUE THREAD

**Issue by jakeoliveroschico** [wangyucode/sftp-upload-action#4]
exclude: "node_modules/,**/*.spec.ts"
excludeMode: "ignore"

Am I doing it wrong?
It's not working for me

**Comment by Evakos** [comment]
Hi,

You are probably using  wangyucode/sftp-upload-action@v1.3.2  in your YML file. Upgrade to 1.3.3 and it should fix your issue.

Chris

**Comment by wangyucode** [comment]
Hi @jakeoliveroschico, 
I have tested the same config as you:
https://github.com/wangyucode/sftp-upload-action/blob/main/.github/workflows/issue-4.yml

and it works as expected:
```
* local dir  = /home/runner/work/sftp-upload-action/sftp-upload-action/project
* remote dir = /project
[ F |   ] index.ts
          -> upload
[ X |   ] node_modules
          -> ignore
[ D |   ] test
          -> sync
[ X |   ] test/index.spec.ts
          -> ignore
[ D |   ] test/utils
          -> sync
[ X |   ] test/utils/util.spec.ts
          -> ignore
```
