### ISSUE TITLE
Ignore emptys files

### ISSUE THREAD

**Issue by Gamermathijs** [wangyucode/sftp-upload-action#5]
When I use:
```
exclude: '!Something.jar'
excludeMode: 'ignore'
```
It emptys the file.

**Comment by Gamermathijs** [comment]
In my testing Something.jar isn't empty the files that already were on the server got empty
I had the files local:
```
SomethingOne.jar
SomethingTwo.jar
```
And on the server:
```
Anothyer.jar
```

And after I uploaded it with the settings: `exclude: '!Something*.jar'` Another.jar would get empty

**Comment by wangyucode** [comment]
Sorry,  I can't reproduce your problem, I created a file on my server, but after running this action, my file has not changed.
if that action fixes your problem,  then use it. 😘
My English is not good too, I am Chinese.😂
